### PR TITLE
Threads next proposal

### PR DESCRIPTION
**Pull request by kalbasit**
Implement `Threads.Next(*Thread)` which makes a for loop a lot nicer.

depends on #2

### CODE REVIEW

**Comment by kalbasit** [comment]
@zenhack this would be a lot cleaner once #2 is merged.

**Comment by zenhack** [comment]
#2 is merged, so I'm not sure why the first commit hasn't disappeared from this pr.

In any case, I think it would be more idiomatic to return a pair `(*Thread, error)` than to pass the result in as an argument. the mongo library does this because it's doing stuff with reflection to unmarshal the results (by way of the bson library), but we just have a static result type. This would be more in line with what `database/sql` does.

Also, in the future, could you try to keep logically separate changes in separate commits? It would have made the patch easier to understand if (for example) renaming the reciever variable `t` to `ts` had been it's own commit; as it is the diff is a bit jumbled.

**Comment by kalbasit** [comment]
I agree with that, however not requiring a pointer will turn the loop from:

```
    thread := &notmuch.Thread{}
    for threads.Next(thread) {
        fmt.Println(thread.GetSubject())
    }
```

to:

```
    for thread, err := threads.Next(); err == nil; thread, err = threads.Next() {
        fmt.Println(thread.GetSubject())
    }
```

or maybe 

```
for {
    thread, err := threads.Next()
    if err != nil {
        break
    }
    fmt.Println(thread.GetSubject())
}
```

so it's a matter of taste, which do you prefer?

**Comment by kalbasit** [comment]
> Also, in the future, could you try to keep logically separate changes in separate commits? It would have made the patch easier to understand if (for example) renaming the reciever variable `t` to `ts` had been it's own commit; as it is the diff is a bit jumbled.

Sure sorry about that. Too many changes happening on my side it's hard to micro-commit. I can definitely do that past #4 as that one has too many changes as well.

**Comment by zenhack** [comment]
Looks good, merged.

Just so it's on the record: We spoke on IRC, decided that the current version (with threads as a parameter) is better, since it's far less verbose.

**Pull request merged**
